// Portfolio.Web/Showcases/Angular/src/app/app.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  HostListener,
  computed,
  effect,
  inject,
  signal,
  viewChild,
  ViewEncapsulation,
} from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';

type SortColumn = 'companyName' | 'contactName' | 'city' | 'country' | 'customerId';

interface CustomerSummary {
  customerId: string;
  companyName: string;
  contactName: string | null;
  city: string | null;
  country: string | null;
}

interface CustomerDetail extends CustomerSummary {
  contactTitle: string | null;
  address: string | null;
  region: string | null;
  postalCode: string | null;
  phone: string | null;
  fax: string | null;
  orderCount: number;
  totalSales: number;
}

interface CustomerPage {
  items: CustomerSummary[];
  totalCount: number;
  totalPages: number;
}

interface CustomerOrder {
  orderId: number;
  orderDate: string | null;
  status: string;
  total: number;
}
interface OrderDetail {
  orderId: number;
  employeeName: string | null;
  shipperName: string | null;
  status: string;
  freight: number;
  subtotal: number;
  total: number;
  shippingAddress: { city: string | null; country: string | null };
  items: {
    productId: number;
    productName: string;
    unitPrice: number;
    quantity: number;
    extendedPrice: number;
  }[];
}

const customerColumns: readonly (readonly [SortColumn, string])[] = [
  ['companyName', 'Company'],
  ['contactName', 'Contact'],
  ['city', 'City'],
  ['country', 'Country'],
  ['customerId', 'ID'],
];
const editableFields: readonly (readonly [keyof CustomerDetail, string])[] = [
  ['companyName', 'Company'],
  ['contactName', 'Contact'],
  ['contactTitle', 'Title'],
  ['address', 'Address'],
  ['city', 'City'],
  ['region', 'Region'],
  ['postalCode', 'Postal code'],
  ['country', 'Country'],
  ['phone', 'Phone'],
  ['fax', 'Fax'],
];

@Component({
  selector: 'app-angular-showcase',
  imports: [ReactiveFormsModule],
  templateUrl: './app.html',
  styleUrl: './app.css',
  encapsulation: ViewEncapsulation.ShadowDom,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class App {
  private readonly formBuilder = inject(FormBuilder);
  private readonly dialog = viewChild.required<ElementRef<HTMLDialogElement>>('profileDialog');

  protected readonly profile = this.formBuilder.nonNullable.group({
    name: ['Ada Lovelace', Validators.required],
    email: ['ada@example.com', [Validators.required, Validators.email]],
    seats: [3, [Validators.required, Validators.min(1), Validators.max(20)]],
    startDate: ['2026-08-01', Validators.required],
    role: ['Developer', Validators.required],
  });
  protected readonly interests = signal(['Data']);
  protected readonly contactMethod = signal('Email');
  protected readonly notificationsEnabled = signal(true);
  protected readonly confidence = signal(72);
  protected readonly activeTab = signal<'summary' | 'settings'>('summary');
  protected readonly notice = signal('');
  protected readonly interestsSummary = computed(() => this.interests().join(', ') || 'None');
  protected readonly columns = customerColumns;
  protected readonly countries = signal<string[]>([]);
  protected readonly customers = signal<CustomerSummary[]>([]);
  protected readonly search = signal('');
  protected readonly country = signal('');
  protected readonly sort = signal<SortColumn>('companyName');
  protected readonly direction = signal<'asc' | 'desc'>('asc');
  protected readonly page = signal(1);
  protected readonly totalCount = signal(0);
  protected readonly totalPages = signal(0);
  protected readonly selectedId = signal<string | null>(null);
  protected readonly loading = signal(true);
  protected readonly customerError = signal('');
  protected readonly customerDetail = signal<CustomerDetail | null>(null);
  protected readonly detailLoading = signal(false);
  protected readonly detailError = signal('');
  protected readonly orders = signal<CustomerOrder[]>([]);
  protected readonly selectedOrderId = signal<number | null>(null);
  protected readonly orderDetail = signal<OrderDetail | null>(null);
  protected readonly ordersLoading = signal(false);
  protected readonly orderLoading = signal(false);
  protected readonly orderError = signal('');
  protected readonly sandboxEnabled = signal(false);
  protected readonly sandboxHasChanges = signal(false);
  protected readonly sandboxExpiresAt = signal<string | null>(null);
  protected readonly sandboxNotice = signal('');
  protected readonly customerDraft = signal<CustomerDetail | null>(null);
  protected readonly revision = signal(0);
  protected readonly editableFields = editableFields;
  protected readonly draftIsDirty = computed(() => {
    const detail = this.customerDetail();
    const draft = this.customerDraft();
    return Boolean(
      detail &&
      draft &&
      editableFields.some(([field]) => (detail[field] ?? '') !== (draft[field] ?? '')),
    );
  });
  protected readonly pageLabel = computed(
    () => `Page ${this.page()} of ${Math.max(this.totalPages(), 1)}`,
  );

  private readonly customerQueryEffect = effect((onCleanup) => {
    const search = this.search().trim();
    const country = this.country();
    const sort = this.sort();
    const direction = this.direction();
    const page = this.page();
    const sandboxEnabled = this.sandboxEnabled();
    this.revision();
    const controller = new AbortController();
    const delay = window.setTimeout(async () => {
      this.loading.set(true);
      this.customerError.set('');
      const parameters = new URLSearchParams({
        sort,
        direction,
        page: String(page),
        pageSize: '10',
      });

      if (search) parameters.set('search', search);
      if (country) parameters.set('country', country);

      try {
        const path = sandboxEnabled
          ? '/api/northwind/sandbox/customers'
          : '/api/northwind/customers';
        const response = await fetch(`${path}?${parameters}`, {
          signal: controller.signal,
        });
        if (!response.ok) throw new Error('Customers could not be loaded.');

        const result = (await response.json()) as CustomerPage;
        this.customers.set(result.items);
        this.totalCount.set(result.totalCount);
        this.totalPages.set(result.totalPages);
        this.selectedId.update((current) =>
          result.items.some((customer) => customer.customerId === current) ? current : null,
        );
      } catch (error) {
        if ((error as Error).name !== 'AbortError') {
          this.customers.set([]);
          this.customerError.set((error as Error).message);
        }
      } finally {
        if (!controller.signal.aborted) this.loading.set(false);
      }
    }, 250);

    onCleanup(() => {
      window.clearTimeout(delay);
      controller.abort();
    });
  });

  private readonly customerDetailEffect = effect((onCleanup) => {
    const selectedId = this.selectedId();
    const sandboxEnabled = this.sandboxEnabled();
    this.revision();
    const controller = new AbortController();

    if (!selectedId) {
      this.customerDetail.set(null);
      this.detailError.set('');
      return;
    }

    this.detailLoading.set(true);
    this.detailError.set('');
    const path = sandboxEnabled
      ? `/api/northwind/sandbox/customers/${selectedId}`
      : `/api/northwind/customers/${selectedId}`;
    fetch(path, {
      signal: controller.signal,
    })
      .then((response) => {
        if (!response.ok) throw new Error('Customer details could not be loaded.');
        return response.json() as Promise<CustomerDetail>;
      })
      .then((detail) => {
        this.customerDetail.set(detail);
        this.customerDraft.set({ ...detail });
      })
      .catch((error: Error) => {
        if (error.name !== 'AbortError') {
          this.customerDetail.set(null);
          this.detailError.set(error.message);
        }
      })
      .finally(() => {
        if (!controller.signal.aborted) this.detailLoading.set(false);
      });

    onCleanup(() => controller.abort());
  });

  private readonly ordersEffect = effect((onCleanup) => {
    const selectedId = this.selectedId();
    const controller = new AbortController();
    if (!selectedId) {
      this.orders.set([]);
      this.selectedOrderId.set(null);
      return;
    }
    this.ordersLoading.set(true);
    this.orderError.set('');
    fetch(`/api/northwind/customers/${selectedId}/orders`, { signal: controller.signal })
      .then((response) => {
        if (!response.ok) throw new Error('Customer orders could not be loaded.');
        return response.json() as Promise<CustomerOrder[]>;
      })
      .then((orders) => {
        this.orders.set(orders);
        this.selectedOrderId.update((current) =>
          orders.some((order) => order.orderId === current)
            ? current
            : (orders[0]?.orderId ?? null),
        );
      })
      .catch((error: Error) => {
        if (error.name !== 'AbortError') this.orderError.set(error.message);
      })
      .finally(() => {
        if (!controller.signal.aborted) this.ordersLoading.set(false);
      });
    onCleanup(() => controller.abort());
  });

  private readonly orderDetailEffect = effect((onCleanup) => {
    const orderId = this.selectedOrderId();
    const controller = new AbortController();
    if (!orderId) {
      this.orderDetail.set(null);
      return;
    }
    this.orderLoading.set(true);
    this.orderError.set('');
    fetch(`/api/northwind/orders/${orderId}`, { signal: controller.signal })
      .then((response) => {
        if (!response.ok) throw new Error('Order details could not be loaded.');
        return response.json() as Promise<OrderDetail>;
      })
      .then((detail) => this.orderDetail.set(detail))
      .catch((error: Error) => {
        if (error.name !== 'AbortError') this.orderError.set(error.message);
      })
      .finally(() => {
        if (!controller.signal.aborted) this.orderLoading.set(false);
      });
    onCleanup(() => controller.abort());
  });

  private readonly sandboxStatusEffect = effect((onCleanup) => {
    if (!this.sandboxEnabled()) return;
    this.revision();
    const controller = new AbortController();
    fetch('/api/northwind/sandbox/status', { signal: controller.signal })
      .then((response) => {
        if (!response.ok) throw new Error('Sandbox status could not be loaded.');
        return response.json() as Promise<{ hasChanges: boolean; expiresAt: string }>;
      })
      .then((status) => {
        this.sandboxHasChanges.set(status.hasChanges);
        this.sandboxExpiresAt.set(status.expiresAt);
      })
      .catch((error: Error) => {
        if (error.name !== 'AbortError') this.sandboxNotice.set(error.message);
      });
    onCleanup(() => controller.abort());
  });

  constructor() {
    void this.loadCountries();
  }

  protected toggleInterest(interest: string): void {
    this.interests.update((current) =>
      current.includes(interest)
        ? current.filter((item) => item !== interest)
        : [...current, interest],
    );
  }

  protected validateProfile(): void {
    if (this.profile.invalid) {
      return;
    }

    this.notice.set('Example profile validated successfully.');
  }

  protected openDialog(): void {
    this.dialog().nativeElement.showModal();
  }

  protected selectTab(tab: 'summary' | 'settings'): void {
    this.activeTab.set(tab);
  }

  protected handleTabKey(event: KeyboardEvent, tab: 'summary' | 'settings'): void {
    if (event.key !== 'ArrowLeft' && event.key !== 'ArrowRight') {
      return;
    }

    event.preventDefault();
    const nextTab = tab === 'summary' ? 'settings' : 'summary';
    this.activeTab.set(nextTab);
    const tabList = (event.currentTarget as HTMLElement).parentElement;
    tabList?.querySelector<HTMLButtonElement>(`#profile-${nextTab}-tab`)?.focus();
  }

  protected updateSearch(value: string): void {
    this.search.set(value);
    this.page.set(1);
  }

  protected updateCountry(value: string): void {
    this.country.set(value);
    this.page.set(1);
  }

  protected changeSort(nextSort: SortColumn): void {
    if (this.sort() === nextSort) {
      this.direction.update((current) => (current === 'asc' ? 'desc' : 'asc'));
    } else {
      this.sort.set(nextSort);
      this.direction.set('asc');
    }
    this.page.set(1);
  }

  protected sortLabel(column: SortColumn): string {
    if (this.sort() !== column) return 'Not sorted';
    return this.direction() === 'asc' ? 'Sorted ascending' : 'Sorted descending';
  }

  protected customerLocation(detail: CustomerDetail): string {
    return [detail.city, detail.region, detail.postalCode, detail.country]
      .filter(Boolean)
      .join(', ');
  }

  protected formatSales(value: number): string {
    return `$${Number(value).toLocaleString()}`;
  }

  protected formatDate(value: string | null): string {
    return value ? new Date(value).toLocaleDateString() : 'No order date';
  }

  protected destination(detail: OrderDetail): string {
    return (
      [detail.shippingAddress.city, detail.shippingAddress.country].filter(Boolean).join(', ') ||
      '—'
    );
  }

  protected toggleSandbox(enabled: boolean): void {
    if (!enabled && this.draftIsDirty()) {
      this.sandboxNotice.set(
        'Save or discard the unsaved customer fields before leaving sandbox mode.',
      );
      return;
    }
    this.sandboxEnabled.set(enabled);
    this.selectedId.set(null);
    this.page.set(1);
    this.sandboxNotice.set('');
  }

  protected updateCustomerDraft(field: keyof CustomerDetail, value: string): void {
    this.customerDraft.update((current) => (current ? { ...current, [field]: value } : current));
  }

  protected discardCustomerDraft(): void {
    const detail = this.customerDetail();
    if (detail) this.customerDraft.set({ ...detail });
    this.sandboxNotice.set('Unsaved field changes discarded.');
  }

  protected async saveSandboxCustomer(): Promise<void> {
    const selectedId = this.selectedId();
    const draft = this.customerDraft();
    if (!selectedId || !draft || !draft.companyName.trim() || !this.draftIsDirty()) return;
    const response = await fetch(`/api/northwind/sandbox/customers/${selectedId}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(draft),
    });
    if (!response.ok) {
      this.sandboxNotice.set('The sandbox customer could not be saved.');
      return;
    }
    this.sandboxNotice.set("Saved to this session's temporary database.");
    this.sandboxHasChanges.set(true);
    this.revision.update((value) => value + 1);
  }

  protected async resetSandbox(): Promise<void> {
    const response = await fetch('/api/northwind/sandbox/reset', { method: 'POST' });
    if (!response.ok) {
      this.sandboxNotice.set('The sandbox could not be reset.');
      return;
    }
    this.selectedId.set(null);
    this.sandboxHasChanges.set(false);
    this.sandboxExpiresAt.set(null);
    this.sandboxNotice.set('Sandbox reset to vanilla Northwind data.');
    this.revision.update((value) => value + 1);
  }

  @HostListener('window:beforeunload', ['$event'])
  protected warnBeforeUnload(event: BeforeUnloadEvent): void {
    if (!this.draftIsDirty()) return;
    event.preventDefault();
    event.returnValue = '';
  }

  private async loadCountries(): Promise<void> {
    try {
      const response = await fetch('/api/northwind/countries');
      if (!response.ok) throw new Error('Countries could not be loaded.');
      this.countries.set((await response.json()) as string[]);
    } catch (error) {
      this.customerError.set((error as Error).message);
    }
  }
}

// Portfolio.Web/Showcases/React/src/App.jsx
import { useEffect, useMemo, useRef, useState } from 'react'
import reactLogo from './assets/react.svg'

const columns = [
  ['companyName', 'Company'],
  ['contactName', 'Contact'],
  ['city', 'City'],
  ['country', 'Country'],
  ['customerId', 'ID'],
]

function App() {
  const [profile, setProfile] = useState({
    name: 'Ada Lovelace',
    email: 'ada@example.com',
    seats: 3,
    startDate: '2026-08-01',
    role: 'Developer',
  })
  const [interests, setInterests] = useState(['Data'])
  const [contactMethod, setContactMethod] = useState('Email')
  const [notificationsEnabled, setNotificationsEnabled] = useState(true)
  const [confidence, setConfidence] = useState(72)
  const [activeTab, setActiveTab] = useState('summary')
  const [notice, setNotice] = useState('')
  const dialogRef = useRef(null)
  const [countries, setCountries] = useState([])
  const [customers, setCustomers] = useState([])
  const [search, setSearch] = useState('')
  const [country, setCountry] = useState('')
  const [sort, setSort] = useState('companyName')
  const [direction, setDirection] = useState('asc')
  const [page, setPage] = useState(1)
  const [totalCount, setTotalCount] = useState(0)
  const [totalPages, setTotalPages] = useState(0)
  const [selectedId, setSelectedId] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const pageSize = 10
  const emailIsValid = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(profile.email)

  function updateProfile(field, value) {
    setProfile((current) => ({ ...current, [field]: value }))
  }

  function toggleInterest(interest) {
    setInterests((current) =>
      current.includes(interest)
        ? current.filter((item) => item !== interest)
        : [...current, interest],
    )
  }

  useEffect(() => {
    const controller = new AbortController()

    fetch('/api/northwind/countries', { signal: controller.signal })
      .then((response) => {
        if (!response.ok) throw new Error('Countries could not be loaded.')
        return response.json()
      })
      .then(setCountries)
      .catch((requestError) => {
        if (requestError.name !== 'AbortError') setError(requestError.message)
      })

    return () => controller.abort()
  }, [])

  const query = useMemo(() => {
    const parameters = new URLSearchParams({
      sort,
      direction,
      page: String(page),
      pageSize: String(pageSize),
    })

    if (search.trim()) parameters.set('search', search.trim())
    if (country) parameters.set('country', country)

    return parameters
  }, [country, direction, page, search, sort])

  useEffect(() => {
    const controller = new AbortController()
    const delay = setTimeout(async () => {
      setLoading(true)
      setError('')

      try {
        const response = await fetch(`/api/northwind/customers?${query}`, {
          signal: controller.signal,
        })

        if (!response.ok) throw new Error('Customers could not be loaded.')

        const result = await response.json()
        setCustomers(result.items)
        setTotalCount(result.totalCount)
        setTotalPages(result.totalPages)
        setSelectedId((current) =>
          result.items.some((customer) => customer.customerId === current)
            ? current
            : null,
        )
      } catch (requestError) {
        if (requestError.name !== 'AbortError') {
          setCustomers([])
          setError(requestError.message)
        }
      } finally {
        if (!controller.signal.aborted) setLoading(false)
      }
    }, 250)

    return () => {
      clearTimeout(delay)
      controller.abort()
    }
  }, [query])

  function changeSort(nextSort) {
    if (sort === nextSort) {
      setDirection((current) => (current === 'asc' ? 'desc' : 'asc'))
    } else {
      setSort(nextSort)
      setDirection('asc')
    }
    setPage(1)
  }

  function sortLabel(column) {
    if (sort !== column) return 'Not sorted'
    return direction === 'asc' ? 'Sorted ascending' : 'Sorted descending'
  }

  return (
    <main className="showcase">
      <header className="showcase-header">
        <div>
          <span className="eyebrow">Frontend Lab</span>
          <h1>React showcase</h1>
          <p>
            Interactive UI patterns and data binding implemented with React
            state, effects, and accessible native controls.
          </p>
        </div>
        <div className="framework-badge">
          <img src={reactLogo} alt="" />
          <span>React</span>
        </div>
      </header>

      <section className="controls-section" aria-labelledby="controls-heading">
        <div className="section-heading">
          <div>
            <span className="eyebrow">Controlled components</span>
            <h2 id="controls-heading">Control gallery</h2>
          </div>
          <p>
            Every value below is held in React state and immediately reflected
            in the live summary.
          </p>
        </div>

        <div className="control-layout">
          <form
            className="control-card form-card"
            onSubmit={(event) => {
              event.preventDefault()
              setNotice('Example profile validated successfully.')
            }}
          >
            <h3>Profile inputs</h3>
            <div className="field-grid">
              <label>
                <span>Name</span>
                <input
                  value={profile.name}
                  onChange={(event) => updateProfile('name', event.target.value)}
                />
              </label>
              <label>
                <span>Email</span>
                <input
                  type="email"
                  value={profile.email}
                  aria-invalid={!emailIsValid}
                  aria-describedby="email-help"
                  onChange={(event) =>
                    updateProfile('email', event.target.value)
                  }
                />
                <small
                  id="email-help"
                  className={emailIsValid ? 'field-help' : 'field-error'}
                >
                  {emailIsValid
                    ? 'Used for example notifications.'
                    : 'Enter a valid email address.'}
                </small>
              </label>
              <label>
                <span>Seats</span>
                <input
                  type="number"
                  min="1"
                  max="20"
                  value={profile.seats}
                  onChange={(event) =>
                    updateProfile('seats', Number(event.target.value))
                  }
                />
              </label>
              <label>
                <span>Start date</span>
                <input
                  type="date"
                  value={profile.startDate}
                  onChange={(event) =>
                    updateProfile('startDate', event.target.value)
                  }
                />
              </label>
              <label className="field-span">
                <span>Role</span>
                <select
                  value={profile.role}
                  onChange={(event) => updateProfile('role', event.target.value)}
                >
                  <option>Developer</option>
                  <option>Designer</option>
                  <option>Analyst</option>
                  <option>Manager</option>
                </select>
              </label>
            </div>

            <fieldset>
              <legend>Interests</legend>
              <div className="choice-row">
                {['Data', 'Design', 'Automation'].map((interest) => (
                  <label className="choice" key={interest}>
                    <input
                      type="checkbox"
                      checked={interests.includes(interest)}
                      onChange={() => toggleInterest(interest)}
                    />
                    <span>{interest}</span>
                  </label>
                ))}
              </div>
            </fieldset>

            <fieldset>
              <legend>Preferred contact</legend>
              <div className="choice-row">
                {['Email', 'Phone', 'Chat'].map((method) => (
                  <label className="choice" key={method}>
                    <input
                      type="radio"
                      name="contact-method"
                      value={method}
                      checked={contactMethod === method}
                      onChange={() => setContactMethod(method)}
                    />
                    <span>{method}</span>
                  </label>
                ))}
              </div>
            </fieldset>

            <div className="form-actions">
              <button
                type="submit"
                className="primary-button"
                disabled={!emailIsValid || !profile.name.trim()}
              >
                Validate profile
              </button>
              <button
                type="button"
                className="secondary-button"
                onClick={() => dialogRef.current?.showModal()}
              >
                Open dialog
              </button>
              <button type="button" className="secondary-button" disabled>
                Disabled
              </button>
            </div>
          </form>

          <div className="control-stack">
            <section className="control-card">
              <h3>Preferences and progress</h3>
              <label className="switch-row">
                <span>
                  <strong>Notifications</strong>
                  <small>Enable status updates</small>
                </span>
                <input
                  className="switch"
                  type="checkbox"
                  role="switch"
                  checked={notificationsEnabled}
                  onChange={(event) =>
                    setNotificationsEnabled(event.target.checked)
                  }
                />
              </label>
              <label className="range-field">
                <span>
                  Confidence <strong>{confidence}%</strong>
                </span>
                <input
                  type="range"
                  min="0"
                  max="100"
                  value={confidence}
                  onChange={(event) => setConfidence(event.target.value)}
                />
              </label>
              <progress
                value={confidence}
                max="100"
                aria-label={`Confidence ${confidence}%`}
              />
            </section>

            <section className="control-card">
              <div className="tabs" role="tablist" aria-label="Profile views">
                {['summary', 'settings'].map((tab) => (
                  <button
                    key={tab}
                    type="button"
                    role="tab"
                    aria-selected={activeTab === tab}
                    onClick={() => setActiveTab(tab)}
                  >
                    {tab[0].toUpperCase() + tab.slice(1)}
                  </button>
                ))}
              </div>
              <div className="tab-panel" role="tabpanel">
                {activeTab === 'summary' ? (
                  <>
                    <h3>{profile.name || 'Unnamed profile'}</h3>
                    <dl className="summary-list">
                      <div>
                        <dt>Role</dt>
                        <dd>{profile.role}</dd>
                      </div>
                      <div>
                        <dt>Seats</dt>
                        <dd>{profile.seats}</dd>
                      </div>
                      <div>
                        <dt>Contact</dt>
                        <dd>{contactMethod}</dd>
                      </div>
                      <div>
                        <dt>Interests</dt>
                        <dd>{interests.join(', ') || 'None'}</dd>
                      </div>
                    </dl>
                  </>
                ) : (
                  <>
                    <h3>Current settings</h3>
                    <p>
                      Notifications are{' '}
                      <strong>
                        {notificationsEnabled ? 'enabled' : 'disabled'}
                      </strong>
                      . The selected start date is {profile.startDate}.
                    </p>
                  </>
                )}
              </div>
              <details>
                <summary>Implementation note</summary>
                <p>
                  Native controls preserve keyboard behavior while React binds
                  each value and derives this summary.
                </p>
              </details>
            </section>
          </div>
        </div>

        {notice && (
          <div className="notification" role="status">
            <span>{notice}</span>
            <button
              type="button"
              aria-label="Dismiss notification"
              onClick={() => setNotice('')}
            >
              ×
            </button>
          </div>
        )}
      </section>

      <section className="data-section" aria-labelledby="data-heading">
        <div className="section-heading">
          <div>
            <span className="eyebrow">API-backed state</span>
            <h2 id="data-heading">Northwind data binding</h2>
          </div>
          <p>
            Server-driven filtering, sorting, paging, and selection against the
            Northwind API.
          </p>
        </div>

        <section className="grid-card" aria-labelledby="customers-heading">
          <div className="grid-heading">
            <div>
              <h3 id="customers-heading">Customer explorer</h3>
              <p>{totalCount} Northwind records</p>
            </div>
            <div className="filters">
              <label>
                <span>Search</span>
                <input
                  type="search"
                  value={search}
                  placeholder="Company or contact"
                  onChange={(event) => {
                    setSearch(event.target.value)
                    setPage(1)
                  }}
                />
              </label>
              <label>
                <span>Country</span>
                <select
                  value={country}
                  onChange={(event) => {
                    setCountry(event.target.value)
                    setPage(1)
                  }}
                >
                  <option value="">All countries</option>
                  {countries.map((item) => (
                    <option key={item} value={item}>
                      {item}
                    </option>
                  ))}
                </select>
              </label>
            </div>
          </div>

          {error && <div className="status error">{error}</div>}

          <div className="table-wrap" aria-busy={loading}>
            <table>
            <thead>
              <tr>
                {columns.map(([key, label]) => (
                  <th key={key} scope="col">
                    <button
                      type="button"
                      className={sort === key ? 'active-sort' : ''}
                      aria-label={`${label}: ${sortLabel(key)}`}
                      onClick={() => changeSort(key)}
                    >
                      {label}
                      <span aria-hidden="true">
                        {sort === key ? (direction === 'asc' ? '↑' : '↓') : '↕'}
                      </span>
                    </button>
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {!loading &&
                customers.map((customer) => (
                  <tr
                    key={customer.customerId}
                    className={
                      selectedId === customer.customerId ? 'selected' : ''
                    }
                    tabIndex="0"
                    aria-selected={selectedId === customer.customerId}
                    onClick={() => setSelectedId(customer.customerId)}
                    onKeyDown={(event) => {
                      if (event.key === 'Enter' || event.key === ' ') {
                        event.preventDefault()
                        setSelectedId(customer.customerId)
                      }
                    }}
                  >
                    <td data-label="Company">{customer.companyName}</td>
                    <td data-label="Contact">{customer.contactName || '—'}</td>
                    <td data-label="City">{customer.city || '—'}</td>
                    <td data-label="Country">{customer.country || '—'}</td>
                    <td data-label="ID">
                      <code>{customer.customerId}</code>
                    </td>
                  </tr>
                ))}
            </tbody>
            </table>

            {loading && <div className="status">Loading customers…</div>}
            {!loading && !error && customers.length === 0 && (
              <div className="status">No customers match these filters.</div>
            )}
          </div>

          <footer className="grid-footer">
            <span>
              {selectedId ? `Selected: ${selectedId}` : 'Select a customer row'}
            </span>
            <div className="pagination">
              <button
                type="button"
                disabled={loading || page <= 1}
                onClick={() => setPage((current) => current - 1)}
              >
                Previous
              </button>
              <span>
                Page {page} of {Math.max(totalPages, 1)}
              </span>
              <button
                type="button"
                disabled={loading || page >= totalPages}
                onClick={() => setPage((current) => current + 1)}
              >
                Next
              </button>
            </div>
          </footer>
        </section>
      </section>

      <dialog ref={dialogRef}>
        <form method="dialog">
          <span className="eyebrow">Native dialog</span>
          <h2>React-controlled launch</h2>
          <p>
            This modal uses the browser dialog element for focus management and
            keyboard dismissal.
          </p>
          <button className="primary-button">Close dialog</button>
        </form>
      </dialog>
    </main>
  )
}

export default App
